# .github/workflows/build-template.yml

name: Build Template

on:
  workflow_call:
    inputs:
      runs-on:
        required: false
        type: string
        default: 'ubuntu-latest'
      java-version:
        required: false
        type: string
        default: '21'
      java-distribution:
        required: false
        type: string
        default: 'zulu'
      skip-tests:
        required: false
        type: boolean
        default: false
jobs:
  compile:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: ${{ inputs.java-distribution }}
          java-version: ${{ inputs.java-version }}

      - name: Build with Maven
        run: mvn clean compile
  test:
    if: ${{ inputs.skip-tests != true }}
    runs-on: ${{ inputs.runs-on }}
    needs: [ compile ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: ${{ inputs.java-distribution }}
          java-version: ${{ inputs.java-version }}

      - name: Build with Maven
        run: mvn clean verify