# .github/workflows/build-template.yml

name: Build Template

on:
  workflow_call:
    inputs:
      java-version:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ inputs.java-version }}

      - name: Build with Maven
        run: mvn clean package

      - name: Upload target directory
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: target/
